<?php
/**
 * @file
 * Contains site_location_time.module.
 */
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\site_location_time\Plugin\Block;

/**
 * Implements hook_theme().
 */
function site_location_time_theme ($existing, $type, $theme, $path) {

  return [
    'site_location_time_block' => [
      'variables' => [
        'city' => NULL,
        'country' => NULL,
        'timezone' => NULL,
        ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function site_location_time_page_attachments(array &$page) {

  $page['#attached']['library'][] = 'site_location_time/clock_js';
}